{"name": "test_add[case_info0]", "status": "passed", "parameters": [{"name": "case_info", "value": "{'case_id': 1, 'module': '登录', 'title': 'login failed', 'data': '{\"username\":\"23\", \"password\": \"1234\"}', 'expected': 'error'}"}], "start": 1644049175625, "stop": 1644049175625, "uuid": "89f6dcd6-32dd-4936-ba70-3e96ff4fc868", "historyId": "c5aeb5b1622992d1487025b9c5b6e022", "testCaseId": "a4b9f2c635a80802701f818745729390", "fullName": "testcase.test_web.test_login.TestLogin#test_add", "labels": [{"name": "tag", "value": "add"}, {"name": "parentSuite", "value": "testcase.test_web"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-9072V9N"}, {"name": "thread", "value": "9372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_web.test_login"}]}