{"name": "test_add[case_info0]", "status": "passed", "attachments": [{"name": "stdout", "source": "98feef74-778e-480a-ad1e-0b549a0085dc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "0da1e0e7-b9c6-4642-b2b2-9eda486f365e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case_info", "value": "{'case_id': 1, 'module': '登录', 'title': 'login failed', 'data': '{\"username\":\"23\", \"password\": \"1234\"}', 'expected': 'error'}"}], "start": 1641473082815, "stop": 1641473082815, "uuid": "5ebdee51-b7d8-45d4-be7d-5a473763245b", "historyId": "092afb80e68c30911a7519a488820875", "testCaseId": "e532d743fe4761fbb260ec08ed2690b1", "fullName": "testcase.test_login.TestLogin#test_add", "labels": [{"name": "tag", "value": "add"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-9072V9N"}, {"name": "thread", "value": "2760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_login"}]}